name: Test shell commands

on: [push, pull_request]

jobs:
  run-logic:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Auto commit
        run: |
          echo "Push"