name: Test shell commands

on: [push]

jobs:
  run-our-env:
    runs-on: ubuntu-latest
    steps:
      - name: Auto commit
        run: |
          pwd
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch 
          git checkout master 
          git branch --set-upstream-to=origin/master
          git pull 
          ls -a